### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by IRediTOTO** [sergiodxa/swr-sync-storage#27]
Hi can you make a simple example for use this? I am trying to save public user info to local.
 I use localStorage with SWR but it not work well.

**Comment by sergiodxa** [comment]
I added a basic example here https://github.com/sergiodxa/swr-sync-storage/tree/master/examples/basic, hope it helps you!

**Comment by IRediTOTO** [comment]
@sergiodxa  this hard with me, but I did it, I must read your  [blog](https://dev.to/sergiodxa/sync-swr-cache-with-web-storage-8fp) to understand :)
Thank you so much, you saved my month for this. 
Btw, can we choose what data will we save to localstorage? 
I have some swr key.

**Comment by IRediTOTO** [comment]
What is the `swr-err` ? Why it apear on storage?

**Comment by sergiodxa** [comment]
This library sync the whole store, the idea is to use it to build offline apps, so you can reopen the app and start with previous data.

About swr-err, SWR in its cache create two keys per each key you use, one with the data and one for the error in case the fetch failed, we sync everything so we also sync this, if you use an array as key you will also see an `arg` before your key and key will also be serialized so it's not an array exactly.
