### ISSUE TITLE
cause the swr's key serialization, it it should do not work with key of Array type

### ISSUE THREAD

**Issue by anc95** [sergiodxa/swr-sync-storage#37]
key serialization: https://github.com/vercel/swr/blob/master/src/cache.ts#L45
think of the using as follow
```
function App() {
  const {data} = useSWR('/api/a');
  const {data} = useSWR(['/api/list', {id: data.id}], fetcher);
}
```
the key may serialize to `/api/list0`, 
{name: 'xxx', age: 'xxx'} will transform to a Incremental number

page1
```js
function App() {
  const {data} = useSWR(['/api/list', {id: '1'}], fetcher);
}
```
page2
```js
function App() {
  const {data} = useSWR(['/api/list', {id: '2'}], fetcher);
}
```

when i open page1 and page2, `['/api/list', {id: '1'}]` and `['/api/list', {id: '2'}]` will be serialized to `/api/list0`, but they stand for a different query. so they may use the error data

**Comment by sergiodxa** [comment]
It's not recommended to use objects inside keys of SWR (you can search for that in the SWR issues where this has been discussed), use arrays with primitive values instead, you can serialize your object if you still want to use an object.
